name: Test Coverage Report

on: [push]

jobs:
    build:
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v2

        - uses: ruby/setup-ruby@v1
            with:
            ruby-version: '3.1.2'
        - uses: maierj/fastlane-action@v2.2.0
            with:
            lane: 'lh_tests_and_code_coverage'
            
            - name: Create Awesome Badge
            uses: schneegans/dynamic-badges-action@v1.4.0
            with:
                auth: ${{ secrets.GITHUB_TOKEN }}
                gistID: af30c96d0823c18718fa89e47a3e990c
                filename: test.json
                label: Coverage
                message: ${{ $COVERAGE }}
                color: orange
